import ExerciseEntity from "../entities/exercise.entity";

const exerciseData: ExerciseEntity[] = [
    {
        pk_exercise: 1,
        name: "remo t",
        last_weight: 40,
        weight: 0,
        repetitions: 15,
        img_url: "https://i.blogs.es/0c65a1/remot1/1366_2000.jpg",
        completed: true,
        status: true
    },
    {
        pk_exercise: 2,
        name: "jalon frontal",
        last_weight: 100,
        weight: 0,
        repetitions: 12,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThCQpKVF4hJprhFDu3p8ROQnPSynzoiBAqsw&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 3,
        name: "espalda hammer",
        last_weight: 70,
        weight: 0,
        repetitions: 10,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuoE3SGfKWsVML2Bo9u9uInZ555ToLho8nEQ&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 4,
        name: "biceps predicador",
        last_weight: 50,
        weight: 0,
        repetitions: 10,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDdPu2I3jmpS1i4DFaUnow2lIck3yZM3eQnQ&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 1,
        name: "remo t",
        last_weight: 40,
        weight: 0,
        repetitions: 15,
        img_url: "https://i.blogs.es/0c65a1/remot1/1366_2000.jpg",
        completed: true,
        status: true,
    },
    {
        pk_exercise: 2,
        name: "jalon frontal",
        last_weight: 100,
        weight: 0,
        repetitions: 12,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThCQpKVF4hJprhFDu3p8ROQnPSynzoiBAqsw&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 3,
        name: "espalda hammer",
        last_weight: 70,
        weight: 0,
        repetitions: 10,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuoE3SGfKWsVML2Bo9u9uInZ555ToLho8nEQ&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 4,
        name: "biceps predicador",
        last_weight: 50,
        weight: 0,
        repetitions: 10,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDdPu2I3jmpS1i4DFaUnow2lIck3yZM3eQnQ&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 1,
        name: "remo t",
        last_weight: 40,
        weight: 0,
        repetitions: 15,
        img_url: "https://i.blogs.es/0c65a1/remot1/1366_2000.jpg",
        completed: true,
        status: true,
    },
    {
        pk_exercise: 2,
        name: "jalon frontal",
        last_weight: 100,
        weight: 0,
        repetitions: 12,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThCQpKVF4hJprhFDu3p8ROQnPSynzoiBAqsw&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 3,
        name: "espalda hammer",
        last_weight: 70,
        weight: 0,
        repetitions: 10,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuoE3SGfKWsVML2Bo9u9uInZ555ToLho8nEQ&s",
        completed: false,
        status: true,
    },
    {
        pk_exercise: 4,
        name: "biceps predicador",
        last_weight: 50,
        weight: 0,
        repetitions: 10,
        img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDdPu2I3jmpS1i4DFaUnow2lIck3yZM3eQnQ&s",
        completed: false,
        status: true,
    }
];

export default exerciseData;